### ISSUE TITLE
Pages shows decimal when maxLength is 6

### ISSUE THREAD

**Issue by romoo** [dominicarrojado/react-typescript-pagination#2]
```jsx
<Pagination currentPage={1} lastPage={23} maxLength={6} />
```

**Comment by dominicarrojado** [comment]
Hey @romoo, thanks for highlighting, for `maxLength`, it should always be an odd number to display the current page in the middle [as mentioned here in my video](https://youtu.be/ZBmAJTwalGQ?t=146). I realized I should probably mention this in my blog post too.
